name: test

on: [push]

jobs:
  test:
    strategy:
       matrix:
         java: [8, 11, 17, 21, 25]	
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'	  
        java-version: ${{ matrix.java }}
    - name: Maven Test
      run: ./mvnw clean test	
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Java 8
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'	  
        java-version: 8
