name: test

on: [push]

jobs:
  test:
    strategy:
       matrix:
         java: [1.8, 11, 13]	
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Maven Test
      run: ./mvnw clean test	
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8		
    - name: Deploy to Sonatype
      run: ./mvnw -B -Drepo.username=${{secrets.SONATYPE_USERNAME}} -Drepo.password=${{secrets.SONATYPE_PASSWORD}} clean deploy -DskipTests=true --settings mySettings.xml
